const BOOKING_STATUS = {
    DOWNPAYMENT: 'DOWNPAYMENT',
    PAID: 'PAID',
}

const FIELD_STATUS = {
    AVAILABLE: 'AVAILABLE',
    MAINTENANCE: 'MAINTENANCE',
}

const FIELD_TYPE = {
    FUTSAL: 'FUTSAL',
    BASKET: 'BASKET',
    MINI_SOCCER: 'MINI SOCCER',
    BADMINTON: 'BADMINTON',
    TENNIS: 'TENNIS'
}

module.exports = {
    BOOKING_STATUS,
    FIELD_STATUS,
    FIELD_TYPE
}
